---
title: Homework 5
author: Steven Chiou
output: pdf_document
---

\centering Due date: Tuesday, December 11

```{R setup, include = FALSE}
knitr::opts_chunk$set(comment = NA, prompt = TRUE)
```
\flushleft
This homework consists of questions proposed by the presenters. 
You are free to choose any five items that include at least one from each presenter.

1. Diagnostics for the Cox Model by **Tianjian Shi**:
    a. Write down the Schoenfeld residuals formula and briefly explain how it works.
    b. Describe the idea that Therneau et al. (1990) proposed to use
martingale residuals in investigating the functional form of
continuous covariate.
  
2. Survival analysis through the eyes of a molecular biologist by **Kelly Daescu**:
    a. List the cons and pros for both the `ggplot2` and `ploty` packages.
    b. Interpret the Nelson-Aalen estimators presented on page 7.
  
3. A brief introduction to `R` `Shiny` by **Jose Alfaro**:
    a. What is the purpose of the UI function in a Shiny app?
    b. List three widgets and their uses.
    
4. Selecting a threshold for long-term survival probabilities and Kaplan-Meier estimator by **Patrick Thompson**:
    
    Suppose that in a laboratory experiment 10 mice are exposed to carcinogens. The experimenter decides to terminate the study after half of the mice are dead and to sacrifice the other half at that time. The survival times of the five expired mice are 4, 5, 8, 9, and 10 weeks. The survival data of the 10 mice are 4, 5, 8, 9, 10, $10^+$, $10^+$, $10^+$, $10^+$, and $10^+$. Assuming that the failure of these mice follows an exponential distribution, estimate the survival rate $\lambda$ and mean survival time $\mu$.