---
title: "Homework 1"
author: "Xinyu Zhang"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

\centering Due date: Thursday, September 20

```{R setup, include = FALSE}
knitr::opts_chunk$set(comment = NA, prompt = TRUE)
```

1. **Textbook problem 1.3** The investigator of a large clinical trial would like to assess factors that might be associated with drop-out over the course of the trial. 
Describe what would be the event and which observations would be considered censored for such a study.

    The event is the participant drops out of the trial before it ends. The observations that the trial ends before the participatant drops out for certain reasons should be considered as censored.

2. Let $T$ be a positive continuous random variable, show $E(T)=\int_0^\infty S(t) \,dt$. \label{est}

    $E(T)=\int_{-\infty}^{\infty} tf(t)dt=\int_{0}^{\infty} tf(t)dt\newline
Let\ u=t\ and \ dv= f(t)dt, \ then \ du=dt \ and \ v=F(t)=-S(t)\newline
uv\bigg|_{0}^{\infty}-\int_{0}^{\infty}vdu=t(-S(t))\bigg|_{0}^{\infty}-\int_{0}^{\infty} -S(t)dt\newline
=0+\int_0^\infty S(t) \,dt=\int_0^\infty S(t) \,dt$
    
3. Question \ref{est} suggests that the area under the survival curve can be interpreted as the expected survival time.
Consider the following hypothetical data set with 10 death times. 
    ```{R}
    dat <- c(43, 110, 113, 28, 73, 31, 89, 65, 66, 76)
    ```
    a. Plot the empirical survival curve.
    ```{R echo=FALSE,message=FALSE}
    library(tidyverse)
    library(survival)
    ```
    ```{R message=FALSE}
    matrix(dat, nrow=length(dat), dimnames = list(NULL, c("death_time")))%>%
    as.data.frame() %>% mutate(surv = 1 - ecdf(death_time)(death_time)) %>% 
    add_row(death_time = 0, surv = 1,.before = 1) %>%
    ggplot(aes(death_time, surv)) + geom_step() + geom_smooth()
    ```
    b. Find the expected survival time for the hypothetical data set.

    ```{R message=FALSE}
    matrix(dat, nrow=length(dat), dimnames = list(NULL, c("death_time"))) %>%
    as.data.frame() %>%
    mutate(surv = 1 - ecdf(death_time)(death_time)) %>%
    add_row(death_time = 0, surv = 1,.before = 1) %>%
    arrange(desc(surv)) %>%
    mutate(time_diff=lead(death_time,default = 0)-death_time) %>%
    summarise(expected_lifetime=sum(time_diff*surv))
    ```
    The expected lifetime is 69.4.

4. Consider a survival time random variable with hazard $\lambda(t) = \frac{1}{10 - t}$ in $[0, 10)$.
    a. Plot the hazard function.

    ```{R message=FALSE}
    matrix(seq(0, 10, length.out = 10000), dimnames = list(NULL, c("t")))%>%
    as.data.frame() %>%
    mutate(lambda = 1/(10-t)) %>%
    ggplot(aes(t,lambda))+geom_line()+ggtitle("Hazard function")
    ```

    b. Plot the survival function.

    $S(t)=\exp(-\int_{0}^{t} \frac{1}{10 - x}dx)=\exp(-(-\ln(10-x)\bigg|_{0}^{t}))=\exp(\ln(10-t)-\ln(10))=\frac{10-t}{10}=1-\frac{t}{10}$

    ```{R message=FALSE}
    matrix(seq(0, 10, length.out = 10000), dimnames = list(NULL, c("t"))) %>%
    as.data.frame() %>%
    mutate(surv = 1-t/10) %>%
    ggplot(aes(t,surv))+geom_line()+ggtitle("Survival function")
    ```

    The distribution of future lifetime is uniform(0,10).

5. Consider a survival time random variable with constant hazard $\lambda = 0.1$ in $[0, 5)$, 
and $\lambda = 0.2$ in $[5, \infty)$. This is known as a piece-wise constant hazard. 
    a. Plot the hazard function.

    ```{R message=FALSE}
    matrix(seq(0, 100, length.out = 10000), dimnames = list(NULL, c("t"))) %>%
    as.data.frame() %>%
    mutate(lambda = 0.1*(t<5)+0.2*(t>=5)) %>%
    ggplot(aes(t,lambda))+geom_line()+ggtitle("Hazard function")
    ```

    b. Plot the survival function.

    $S(t)=\begin{cases}\exp(-\int_{0}^{t} 0.1dx)=\exp(-0.1t) & t\in[0,5)\\\\\exp(-0.1\times5)\cdot\exp(-\int_{5}^{t-5} 0.2dx)\\=\exp(-0.5)\cdot\exp(1-0..2t)=\exp(0.5-0.2t) & t\in[5,\infty)\end{cases}$

    ```{R}
    matrix(seq(0, 100, length.out = 10000), dimnames = list(NULL, c("t"))) %>%
    as.data.frame() %>%
    mutate(surv = exp(-0.1*t)*(t<5)+exp(0.5-0.2*t)*(t>=5)) %>%
    ggplot(aes(t,surv))+geom_line()+ggtitle("Survival function")
    ```